name: "Auto NotPix HeyahFox"

on:
  schedule:
    - cron: "9 2-11 * * *"  # Minute/Hour/Day/Month/Weekday (UTC)
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
      - name: Copy file from another location
        run: |
          cp sessionsMain/accountsHeyahFox.json sessions/accounts.json
          cp sessionsMain/HeyahFox.session sessions/HeyahFox.session

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 ./main.py -a 1

      - name: Commit and Push Changes
        run: |
            git config --global user.email "oliynik.v2014@gmail.com"
            git config --global user.name "slavikfoxy"
            git remote set-url origin https://$GH_TOKEN@github.com/${{ github.repository }}
            git status
            git add Balances.txt
            git add user_agents.json
            git commit -am "Add new files and modify existing files"
            git push 
          
